name: Generate PRs

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate latest PR information
        uses: "actions/checkout@v2"
        run: docker-compose -f docker/docker-compose.yaml pull_request_action up --build
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
      - name: Create Pull Request with new PRs
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          title: Update PRs
          labels: automerge
          signoff: true
          delete-branch: true
          commit-message: Update PRs
