name: Get Contributors

on:
  schedule:
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate latest release information
        uses: "actions/checkout@v2"
      - uses: BobAnkh/add-contributors@v0.1.0
        with:
          REPO_NAME: 'arsulegai/hyperledger-updates'
          CONTRIBUTOR: '# Backend Contributors'
          COLUMN_PER_ROW: '6'
          ACCESS_TOKEN: ${{ secrets.PAT }}
          IMG_WIDTH: '100'
          FONT_SIZE: '14'
          PATH: '/index.md'
          COMMIT_MESSAGE: 'Update contributors'
          AVATAR_SHAPE: 'round'
